//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordinator
    {
        public Coordinator()
        {
            this.Donor = new HashSet<Donor>();
            this.Donor1 = new HashSet<Donor>();
            this.TransplantOrgan = new HashSet<TransplantOrgan>();
        }
    
        public int ID { get; set; }
        public Nullable<int> HospitalID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Code { get; set; }
        public Nullable<int> AddressID { get; set; }
        public bool IsNC { get; set; }
        public bool IsTC { get; set; }
        public bool isActive { get; set; }
        public byte[] ModificationVersion { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual ICollection<Donor> Donor { get; set; }
        public virtual ICollection<Donor> Donor1 { get; set; }
        public virtual ICollection<TransplantOrgan> TransplantOrgan { get; set; }
    }
}
