//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostDistribution
    {
        public CostDistribution()
        {
            this.OrganCostDistribution = new HashSet<OrganCostDistribution>();
        }
    
        public int ID { get; set; }
        public int CostTypeID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> ForAllOrgans { get; set; }
        public bool CalcTotal { get; set; }
        public Nullable<decimal> TotalConst { get; set; }
        public Nullable<int> MinOrganCount { get; set; }
        public Nullable<int> MaxOrganCount { get; set; }
        public bool ReferOnlyOnTransplantedOrgans { get; set; }
    
        public virtual CostType CostType { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<OrganCostDistribution> OrganCostDistribution { get; set; }
    }
}
