//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public Cost()
        {
            this.OrganCost = new HashSet<OrganCost>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CostTypeID { get; set; }
        public string Name { get; set; }
        public string KreditorName { get; set; }
        public Nullable<int> KreditorHospitalID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> DonorID { get; set; }
        public Nullable<int> TransportID { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] ModificationVersion { get; set; }
        public Nullable<int> CreditorID { get; set; }
    
        public virtual CostType CostType { get; set; }
        public virtual Creditor Creditor { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual ICollection<OrganCost> OrganCost { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
