//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelayReason
    {
        public DelayReason()
        {
            this.Delay = new HashSet<Delay>();
        }
    
        public int ID { get; set; }
        public string Reason { get; set; }
    
        public virtual ICollection<Delay> Delay { get; set; }
    }
}
