//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distance
    {
        public int ID { get; set; }
        public int Hospital1ID { get; set; }
        public int Hospital2ID { get; set; }
        public Nullable<int> Km { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual Hospital Hospital1 { get; set; }
    }
}
