//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public Donor()
        {
            this.Cost = new HashSet<Cost>();
            this.TransplantOrgan = new HashSet<TransplantOrgan>();
            this.Transport = new HashSet<Transport>();
        }
    
        public int ID { get; set; }
        public string DonorNumber { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> ReferralHospitalID { get; set; }
        public Nullable<int> ProcurementHospitalID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> ProcurementDate { get; set; }
        public Nullable<int> NCID { get; set; }
        public Nullable<int> TCID { get; set; }
        public bool IsArchived { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] ModificationVersion { get; set; }
        public Nullable<int> DetectionHospitalID { get; set; }
        public string Comment { get; set; }
        public bool IncisionMade { get; set; }
        public bool Nut { get; set; }
        public Nullable<int> ID_DonationPathway { get; set; }
    
        public virtual Coordinator Coordinator { get; set; }
        public virtual Coordinator Coordinator1 { get; set; }
        public virtual ICollection<Cost> Cost { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Hospital Hospital1 { get; set; }
        public virtual Hospital Hospital2 { get; set; }
        public virtual ICollection<TransplantOrgan> TransplantOrgan { get; set; }
        public virtual ICollection<Transport> Transport { get; set; }
        public virtual DonationPathway DonationPathway { get; set; }
    }
}
