//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Font
    {
        public Font()
        {
            this.ReminderLetter = new HashSet<ReminderLetter>();
        }
    
        public int ID { get; set; }
        public string FontName { get; set; }
        public int FontSize { get; set; }
    
        public virtual ICollection<ReminderLetter> ReminderLetter { get; set; }
    }
}
