//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public Hospital()
        {
            this.Coordinator = new HashSet<Coordinator>();
            this.Cost = new HashSet<Cost>();
            this.Distance = new HashSet<Distance>();
            this.Distance1 = new HashSet<Distance>();
            this.Donor = new HashSet<Donor>();
            this.Donor1 = new HashSet<Donor>();
            this.Donor2 = new HashSet<Donor>();
            this.TransplantOrgan = new HashSet<TransplantOrgan>();
            this.TransplantOrgan1 = new HashSet<TransplantOrgan>();
            this.IncidentAlert = new HashSet<IncidentAlert>();
            this.Transport = new HashSet<Transport>();
            this.Transport1 = new HashSet<Transport>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Display { get; set; }
        public int AddressID { get; set; }
        public bool IsReferral { get; set; }
        public bool IsProcurement { get; set; }
        public bool IsTransplantation { get; set; }
        public bool IsFo { get; set; }
        public bool isActive { get; set; }
        public byte[] ModificationVersion { get; set; }
        public Nullable<int> CorrespondanceLanguageID { get; set; }
        public Nullable<int> AccountingAddressID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ICollection<Coordinator> Coordinator { get; set; }
        public virtual ICollection<Cost> Cost { get; set; }
        public virtual ICollection<Distance> Distance { get; set; }
        public virtual ICollection<Distance> Distance1 { get; set; }
        public virtual ICollection<Donor> Donor { get; set; }
        public virtual ICollection<Donor> Donor1 { get; set; }
        public virtual ICollection<Donor> Donor2 { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<TransplantOrgan> TransplantOrgan { get; set; }
        public virtual ICollection<TransplantOrgan> TransplantOrgan1 { get; set; }
        public virtual ICollection<IncidentAlert> IncidentAlert { get; set; }
        public virtual ICollection<Transport> Transport { get; set; }
        public virtual ICollection<Transport> Transport1 { get; set; }
    }
}
