//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentMail
    {
        public int ID { get; set; }
        public int IncidentStateID { get; set; }
        public string To { get; set; }
        public string Subject { get; set; }
        public string BodyText { get; set; }
        public bool blnEditBefore { get; set; }
        public string ReplyTo { get; set; }
    
        public virtual IncidentState IncidentState { get; set; }
    }
}
