//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentAlert
    {
        public IncidentAlert()
        {
            this.Hospital = new HashSet<Hospital>();
        }
    
        public int ID { get; set; }
        public int IncidentID { get; set; }
        public string AlertMessage { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Incident Incident { get; set; }
        public virtual ICollection<Hospital> Hospital { get; set; }
    }
}
