//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentLexicon
    {
        public IncidentLexicon()
        {
            this.IncidentLexiconDocument = new HashSet<IncidentLexiconDocument>();
        }
    
        public int ID { get; set; }
        public string Definition { get; set; }
        public string Description { get; set; }
        public string InfoDescription { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<IncidentLexiconDocument> IncidentLexiconDocument { get; set; }
    }
}
