//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentDonorRelatedTransport
    {
        public int ID { get; set; }
        public int IncidentID { get; set; }
        public int TransportID { get; set; }
    
        public virtual Incident Incident { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
