//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentState
    {
        public IncidentState()
        {
            this.Incident = new HashSet<Incident>();
            this.IncidentMail = new HashSet<IncidentMail>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual ICollection<Incident> Incident { get; set; }
        public virtual ICollection<IncidentMail> IncidentMail { get; set; }
    }
}
