//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentLexiconDocument
    {
        public int ID { get; set; }
        public int IncidentLexiconID { get; set; }
        public string IncidentLexiconDocumentName { get; set; }
        public string IncidentLexiconDocumentFileType { get; set; }
        public byte[] IncidentLexiconDocumentFileData { get; set; }
    
        public virtual IncidentLexicon IncidentLexicon { get; set; }
    }
}
