//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentProcessToCategory
    {
        public int ID { get; set; }
        public int IncidentCategoryID { get; set; }
        public int IncidentProcessID { get; set; }
    
        public virtual IncidentCategory IncidentCategory { get; set; }
        public virtual IncidentProcess IncidentProcess { get; set; }
    }
}
