//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentDocument
    {
        public int ID { get; set; }
        public Nullable<int> IncidentID { get; set; }
        public string IncidentGUID { get; set; }
        public string IncidentDocumentName { get; set; }
        public string IncidentDocumentFileType { get; set; }
        public byte[] IncidentDocumentFileData { get; set; }
    
        public virtual Incident Incident { get; set; }
    }
}
