//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemGroup
    {
        public ItemGroup()
        {
            this.Organ = new HashSet<Organ>();
            this.TransportItem = new HashSet<TransportItem>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public short Type { get; set; }
        public bool isActive { get; set; }
        public byte[] ModificationVersion { get; set; }
    
        public virtual ICollection<Organ> Organ { get; set; }
        public virtual ICollection<TransportItem> TransportItem { get; set; }
    }
}
