//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganCost
    {
        public int ID { get; set; }
        public Nullable<int> CostID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> TransplantOrganID { get; set; }
        public string Comment { get; set; }
        public byte[] ModificationVersion { get; set; }
    
        public virtual Cost Cost { get; set; }
        public virtual TransplantOrgan TransplantOrgan { get; set; }
    }
}
