//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordResetToken
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Token { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
