//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Address { get; set; }
        public DbSet<Coordinator> Coordinator { get; set; }
        public DbSet<Cost> Cost { get; set; }
        public DbSet<CostDistribution> CostDistribution { get; set; }
        public DbSet<CostGroup> CostGroup { get; set; }
        public DbSet<CostType> CostType { get; set; }
        public DbSet<Creditor> Creditor { get; set; }
        public DbSet<Delay> Delay { get; set; }
        public DbSet<DelayReason> DelayReason { get; set; }
        public DbSet<Distance> Distance { get; set; }
        public DbSet<Donor> Donor { get; set; }
        public DbSet<Font> Font { get; set; }
        public DbSet<Hospital> Hospital { get; set; }
        public DbSet<Incident> Incident { get; set; }
        public DbSet<IncidentAlert> IncidentAlert { get; set; }
        public DbSet<IncidentCategory> IncidentCategory { get; set; }
        public DbSet<IncidentDamageCategory> IncidentDamageCategory { get; set; }
        public DbSet<IncidentLexicon> IncidentLexicon { get; set; }
        public DbSet<IncidentLexiconDocument> IncidentLexiconDocument { get; set; }
        public DbSet<IncidentLikelihoodToRepeat> IncidentLikelihoodToRepeat { get; set; }
        public DbSet<IncidentPotentialDamage> IncidentPotentialDamage { get; set; }
        public DbSet<IncidentProcess> IncidentProcess { get; set; }
        public DbSet<IncidentState> IncidentState { get; set; }
        public DbSet<IncidentTask> IncidentTask { get; set; }
        public DbSet<ItemGroup> ItemGroup { get; set; }
        public DbSet<Language> Language { get; set; }
        public DbSet<OperationCenter> OperationCenter { get; set; }
        public DbSet<Organ> Organ { get; set; }
        public DbSet<OrganCost> OrganCost { get; set; }
        public DbSet<OrganCostDistribution> OrganCostDistribution { get; set; }
        public DbSet<Organization> Organization { get; set; }
        public DbSet<OrganToTransportItemAssociation> OrganToTransportItemAssociation { get; set; }
        public DbSet<ReminderLetter> ReminderLetter { get; set; }
        public DbSet<TransplantOrgan> TransplantOrgan { get; set; }
        public DbSet<TransplantStatus> TransplantStatus { get; set; }
        public DbSet<TransportItem> TransportItem { get; set; }
        public DbSet<Vehicle> Vehicle { get; set; }
        public DbSet<SLIDS> SLIDS { get; set; }
        public DbSet<StatsDonor> StatsDonor { get; set; }
        public DbSet<StatsOrgans> StatsOrgans { get; set; }
        public DbSet<StatsTransports> StatsTransports { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<IncidentMail> IncidentMail { get; set; }
        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public DbSet<IncidentDocument> IncidentDocument { get; set; }
        public DbSet<IncidentDonorRelatedDelay> IncidentDonorRelatedDelay { get; set; }
        public DbSet<IncidentDonorRelatedOrgan> IncidentDonorRelatedOrgan { get; set; }
        public DbSet<IncidentDonorRelatedTransport> IncidentDonorRelatedTransport { get; set; }
        public DbSet<IncidentProcessToCategory> IncidentProcessToCategory { get; set; }
        public DbSet<IncidentAnalysis> IncidentAnalysis { get; set; }
        public DbSet<Lifeport> Lifeport { get; set; }
        public DbSet<Transport> Transport { get; set; }
        public DbSet<TransportedOrgan> TransportedOrgan { get; set; }
        public DbSet<DonationPathway> DonationPathway { get; set; }
        public DbSet<PasswordResetToken> PasswordResetTokens { get; set; }
    }
}
