//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatsOrgans
    {
        public string Donor_Number { get; set; }
        public string Procurement_Hospital { get; set; }
        public Nullable<System.DateTime> Register_Date { get; set; }
        public Nullable<System.DateTime> Procurement_Date { get; set; }
        public string Organ { get; set; }
        public string Transplantation_Center { get; set; }
        public string Transplant_Coordinator { get; set; }
        public string Procurement_Team { get; set; }
        public string Procurement_Surgeon { get; set; }
        public string Necro_Report_within_5_days { get; set; }
        public string Transplant_Status { get; set; }
        public string Lifeport { get; set; }
        public string Ex_Vivo { get; set; }
        public string Hope { get; set; }
    }
}
