//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatsDonor
    {
        public string Donor_Number { get; set; }
        public string Detection_Hospital { get; set; }
        public string Referral_Hospital { get; set; }
        public string Procurement_Hospital { get; set; }
        public Nullable<System.DateTime> Register_Date { get; set; }
        public Nullable<System.DateTime> Procurement_Date { get; set; }
        public string Transplant_Coordinator { get; set; }
        public string Organization { get; set; }
        public string National_Coordinator { get; set; }
        public string Comment { get; set; }
        public string Incision_made { get; set; }
    }
}
