//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatsTransports
    {
        public string Donor_Number { get; set; }
        public string Procurement_Hospital { get; set; }
        public Nullable<System.DateTime> Register_Date { get; set; }
        public Nullable<System.DateTime> Procurement_Date { get; set; }
        public string Departure { get; set; }
        public string Destination { get; set; }
        public string Organs { get; set; }
        public string Items { get; set; }
        public Nullable<int> OrganCount { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<System.DateTime> Departed { get; set; }
        public Nullable<System.DateTime> Arrived { get; set; }
        public Nullable<int> Waiting_Time { get; set; }
        public string Vehicle { get; set; }
        public string Police_Escorted { get; set; }
        public string FlightNumber { get; set; }
        public string Immatriculation { get; set; }
        public string Operation_Center { get; set; }
        public string Provider { get; set; }
        public Nullable<int> Forewarning { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Delay { get; set; }
        public string Delay_Reason { get; set; }
        public string Organ_lost_due_to_delay { get; set; }
        public string Delay_comment { get; set; }
    }
}
