//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportItem
    {
        public TransportItem()
        {
            this.OrganToTransportItemAssociation = new HashSet<OrganToTransportItemAssociation>();
            this.Transport = new HashSet<Transport>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Position { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> CountableAs { get; set; }
        public Nullable<int> ItemGroupID { get; set; }
    
        public virtual ItemGroup ItemGroup { get; set; }
        public virtual ICollection<OrganToTransportItemAssociation> OrganToTransportItemAssociation { get; set; }
        public virtual ICollection<Transport> Transport { get; set; }
    }
}
