//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public Transport()
        {
            this.Cost = new HashSet<Cost>();
            this.Delay = new HashSet<Delay>();
            this.IncidentDonorRelatedTransport = new HashSet<IncidentDonorRelatedTransport>();
            this.TransportedOrgan = new HashSet<TransportedOrgan>();
            this.TransplantOrgan = new HashSet<TransplantOrgan>();
            this.TransportItem = new HashSet<TransportItem>();
        }
    
        public int ID { get; set; }
        public int DonorID { get; set; }
        public Nullable<int> Forewarning { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public bool PoliceEscorted { get; set; }
        public Nullable<int> DepartureHospitalID { get; set; }
        public string OtherDeparture { get; set; }
        public Nullable<int> DestinationHospitalID { get; set; }
        public string OtherDestination { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public string FlightNumber { get; set; }
        public string Immatriculation { get; set; }
        public Nullable<int> WaitingTime { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> OperationCenterID { get; set; }
        public string Provider { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] ModificationVersion { get; set; }
    
        public virtual ICollection<Cost> Cost { get; set; }
        public virtual ICollection<Delay> Delay { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual Hospital Hospital1 { get; set; }
        public virtual ICollection<IncidentDonorRelatedTransport> IncidentDonorRelatedTransport { get; set; }
        public virtual OperationCenter OperationCenter { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<TransportedOrgan> TransportedOrgan { get; set; }
        public virtual ICollection<TransplantOrgan> TransplantOrgan { get; set; }
        public virtual ICollection<TransportItem> TransportItem { get; set; }
    }
}
