//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransplantOrgan
    {
        public TransplantOrgan()
        {
            this.OrganCost = new HashSet<OrganCost>();
            this.IncidentDonorRelatedOrgan = new HashSet<IncidentDonorRelatedOrgan>();
            this.TransportedOrgan = new HashSet<TransportedOrgan>();
            this.Transport = new HashSet<Transport>();
        }
    
        public int ID { get; set; }
        public int DonorID { get; set; }
        public int OrganID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> TransplantCenterID { get; set; }
        public Nullable<int> TCID { get; set; }
        public Nullable<int> GraftBoxNo { get; set; }
        public Nullable<int> ProcurementTeamID { get; set; }
        public string ProcurementSurgeon { get; set; }
        public Nullable<bool> ReceivedNecroReportWithin5Days { get; set; }
        public Nullable<int> TransplantStatusID { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] ModificationVersion { get; set; }
        public Nullable<bool> PrefusionMachine { get; set; }
        public string PrefusionMachineNumber { get; set; }
        public string Remark { get; set; }
    
        public virtual Coordinator Coordinator { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual Hospital Hospital1 { get; set; }
        public virtual Organ Organ { get; set; }
        public virtual ICollection<OrganCost> OrganCost { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual TransplantStatus TransplantStatus { get; set; }
        public virtual ICollection<IncidentDonorRelatedOrgan> IncidentDonorRelatedOrgan { get; set; }
        public virtual ICollection<TransportedOrgan> TransportedOrgan { get; set; }
        public virtual ICollection<Transport> Transport { get; set; }
    }
}
