//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentag.SLIDS.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class TransportLifeport
    {
        public int ID { get; set; }
        public int LifeportID { get; set; }
        public int TransportID { get; set; }

        public virtual Lifeport Lifeport { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
